### ISSUE TITLE
Searching by room capacity

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/RoomMe#100]
Users have requested being able to search by room capacity.  So you could limit your search to rooms that hold more than 5 people that are available at the DCL, for example.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/189432508432304/195291938449033)

**Comment by trmccormick** [comment]
This has been added and the branch has been merged into location based permissions since that branch was what I was currently working on. A pull request has been made on this branch so Dave can do a code review.

**Comment by trmccormick** [comment]
Dave will do a code review later today on the changes.
