### ISSUE TITLE
Scheduling Limits

### ISSUE THREAD

**Issue by timbroadwater** [wvulibraries/RoomMe#79]
Users should be limited in scheduling to six hour/policy intervals in dropdowns instead of being allowed to schedule the default 23 hours. Also, limit users to scheduling only so many weeks or hours into the future based on policies; don’t present options or scheduling if it’s not possible to accomplish.

**Comment by MichaelRBond** [comment]
Drop down duration is now limited to the max value of the room policy.

**Comment by MichaelRBond** [comment]
The month, day, year options use the EngineAPI date module to generate the drop downs. It doesn't currently support limiting like this.  This has been added as an enhancement for EngineAPI: 
https://github.com/wvulibraries/engineAPI/issues/25
