### ISSUE TITLE
Room Results

### ISSUE THREAD

**Issue by timbroadwater** [wvulibraries/RoomMe#80]
Reservation results should appear at the top of the page in list format rather than at the bottom in a table format, if rooms are disabled for renting during the summer, they shouldn’t populate on the building list at all, and unavailable rooms should be marked as such.

Also, list unavailable rooms on mobile in red and parenthetically cite ‘reserved’ or ‘unavailable’ afterwards, and make search results always populate at the top of the page.

**Comment by MichaelRBond** [comment]
Rooms displaying is an option in the system. There are some rooms that they want to display, but keep int he list, when they are closed. Others they do not. All of those settings are options that the room admins can set on a per room, per room template, or per building basis.

**Comment by MichaelRBond** [comment]
I'm not sure which page the comment concerning "Also, list unavailable rooms on mobile in red and parenthetically cite ‘reserved’ or ‘unavailable’ afterwards, and make search results always populate at the top of the page." refers too.

**Comment by MichaelRBond** [comment]
Is the first comment referring to individual room pages? 

I can't visualize how a list instead of a table would work (assuming i'm thinking of the correct page). I'll need to see an example before I start programming it.

**Comment by timbroadwater** [comment]
I'm breaking this up into three separate tickets. This one will stay **Reservation results should appear at the top of the page in list format rather than at the bottom in a table format.**
