### ISSUE TITLE
Hours feed not restricting reservations for PSC.

### ISSUE THREAD

**Issue by jetapia** [wvulibraries/RoomMe#94]
PSC's hours are linked in the admin interface, but they aren't restricting reservations when the library is closed.  For example, PSC closes at 9 M-Th, but I can still make reservations for 10pm.

**Comment by jetapia** [comment]
![roomsadmin](https://cloud.githubusercontent.com/assets/10031189/18210207/676bb316-7105-11e6-957a-24a32927d609.gif)

**Comment by MichaelRBond** [comment]
When you go to the hours RSS URL, what do you receive?

**Comment by jetapia** [comment]
943938000|944024400

**Comment by jetapia** [comment]
I think I found the problem.  The RSS URL was incorrect, but I fixed it.
