### ISSUE TITLE
Rooms Delete Button

### ISSUE THREAD

**Issue by ddavisgraphics** [wvulibraries/RoomMe#95]
The delete button for rooms is currently not working in the admin interface.

**Comment by MichaelRBond** [comment]
I believe it has been disabled on purpose. 

If you delete a room, the identifier in the reservations mysql table no longer points to a valid room and it legacy statistics will become meaningless. 

I think a better solution than "delete" would be a "hide". Create a new column in the database on rooms called "deleted", default value = 0. set it to 1 when the delete button is clicked. 

Additional logic will need to be used when listing rooms on both the public and staff interfaces. There would also need to be a trash can. From the trash can they should be able to really-real delete the rooms, but there should be a huge GeoCities style warning on the page about statistics, and a javascript alert asking if they understand the warnings.

**Comment by ddavisgraphics** [comment]
This issue is resolved, after speaking with stake holders this issue is done by expiring the room or placing the room in construction.
