### ISSUE TITLE
Edit room overflows the container. Is this on purpose?

### ISSUE THREAD

**Issue by 9034725985** [wvulibraries/RoomMe#96]
Very excited to see this project. Thank you for publishing. 

This isn't really as much of an issue as it is a question. The edit rooms overflows the container. 

![Is this on purpose?](https://cloud.githubusercontent.com/assets/1676445/18649550/15496600-7e8e-11e6-8eb6-7973fa3162e4.png)

**Comment by ddavisgraphics** [comment]
Thanks for putting in the help desk ticket, we will work on addressing the issue.

**Comment by wvu-libraries** [comment]
➤ Dave Davis commented:
Issue has been resolved, look for it in the next pull-request.

**Comment by trmccormick** [comment]
A pull request has been created for the location based permissions that contains the fix for this issue.

**Comment by trmccormick** [comment]
Dave will do a code review later today.
